import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/Wrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import { ScrollArea } from "@/components/ui/scroll-area";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          <Wrapper>
            <div className="flex flex-col h-screen w-full">
              <Navbar />
              <main className="flex-col flex-1 h-full w-full overflow-y-auto">
                {children}
              </main>
              {/* <ScrollArea className="flex-col flex-1 h-full w-full overflow-auto">
                {children}
              </ScrollArea> */}
              <Footer />
            </div>
          </Wrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}